// @ts-check
const { test, expect } = require("@playwright/test");
const { safeGoto } = require("../helpers");
require("dotenv").config();

const BASE_URL = process.env.BASE_URL;

test("Category List Sc - Snapshot", async ({ page }) => {
  await safeGoto(page, `${BASE_URL}/category-list-sc/`);
  const content = page.locator("main#content");
  await expect(content).toBeVisible({ timeout: 10000 });
  await expect(content).toMatchAriaSnapshot(`
    - main:
      - heading "Category List SC" [level=1]
      - article:
        - heading "MSF" [level=2]
        - list:
          - listitem:
            - link "NBR Chairman signals possible VAT, turnover tax reforms for jewellery businesses":
              - /url: https://betteromation.shahrear.site/docs/nbr-chairman-signals-possible-vat-turnover-tax-reforms-for-jewellery-businesses/
      - article:
        - heading "Star" [level=2]
        - list:
          - listitem:
            - link "NBR says most gold entering country is illegal; Bajus urges licenses for genuine traders":
              - /url: https://betteromation.shahrear.site/docs/nbr-says-most-gold-entering-country-is-illegal-bajus-urges-licenses-for-genuine-traders/
      - article:
        - heading "JuniorQA" [level=2]
        - list:
          - listitem:
            - link "QA Glossary Test for BetterDocs":
              - /url: https://betteromation.shahrear.site/docs/qa-glossary-test-for-betterdocs/
          - listitem:
            - link "Junior QA – The Sprit House":
              - /url: https://betteromation.shahrear.site/docs/junior-qa-the-sprit-house/
      - article:
        - heading "Developer" [level=2]
        - list:
          - listitem:
            - link "Developers, QA, Support – the Engines of A Software Team":
              - /url: https://betteromation.shahrear.site/docs/developers-qa-support-the-engines-of-a-software-team/
      - article:
        - heading "Coleads" [level=2]
        - list:
          - listitem:
            - link "Ovi – The Co Lead of QA Team":
              - /url: https://betteromation.shahrear.site/docs/ovi-the-co-lead-of-qa-team/
          - listitem:
            - link "Hurram – The Co Lead of Security Team":
              - /url: https://betteromation.shahrear.site/docs/hurram-the-co-lead-of-security-team/
      - article:
        - heading "Leads" [level=2]
        - list:
          - listitem:
            - link "Sejuti – The Leader of QA Team":
              - /url: https://betteromation.shahrear.site/docs/sejuti-the-leader-of-qa-team/
      - article:
        - heading "Watermelon" [level=2]
        - list:
          - listitem:
            - link "Importance of Multi Vitamin in Life":
              - /url: https://betteromation.shahrear.site/docs/importance-of-multi-vitamin-in-life/
          - listitem:
            - link "Juice vs Direct Fruit":
              - /url: https://betteromation.shahrear.site/docs/juice-vs-direct-fruit/
          - listitem:
            - link "Watermelon – A Juicy Fruit":
              - /url: https://betteromation.shahrear.site/docs/watermelon-a-juicy-fruit/
      - article:
        - heading "Orange" [level=2]
        - list:
          - listitem:
            - link "Orange – A Favorite Fruit of Children":
              - /url: https://betteromation.shahrear.site/docs/orange-a-favorite-fruit-of-children/
          - listitem:
            - link "The Fruit that Named after Color":
              - /url: https://betteromation.shahrear.site/docs/the-fruit-that-named-after-color/
          - listitem:
            - link "Orange – The Source of Vitamin C":
              - /url: https://betteromation.shahrear.site/docs/orange-the-source-of-vitamin-c/
      - article:
        - heading "Apple" [level=2]
        - list:
          - listitem:
            - link "Apple – A Daily Fruit":
              - /url: https://betteromation.shahrear.site/docs/apple-a-daily-fruit/
      - article:
        - heading "Fencing" [level=2]
        - list:
          - listitem:
            - link "Fencing – The Beautiful Sport":
              - /url: https://betteromation.shahrear.site/docs/fencing-the-beautiful-sport/
      - article:
        - heading "Golf" [level=2]
        - list:
          - listitem:
            - link "Golf – The Game of Patience and Dedication":
              - /url: https://betteromation.shahrear.site/docs/golf-the-game-of-patience-and-dedication/
      - article:
        - heading "Basketball" [level=2]
        - list:
          - listitem:
            - link "Basketball – The Game of Sprit":
              - /url: https://betteromation.shahrear.site/docs/basketball-the-game-of-sprit/
      - article:
        - heading "Football" [level=2]
        - list:
          - listitem:
            - link "Football World Cup 2014":
              - /url: https://betteromation.shahrear.site/docs/football-world-cup-2014/
      - article:
        - heading "Cricket" [level=2]
        - list:
          - listitem:
            - link "Cricket – The Gentlemen’s Game":
              - /url: https://betteromation.shahrear.site/docs/cricket-the-gentlemens-game/
      - paragraph:
        - strong: Customized
      - article:
        - heading "Watermelon" [level=2]
        - list:
          - listitem:
            - link "Importance of Multi Vitamin in Life":
              - /url: https://betteromation.shahrear.site/docs/importance-of-multi-vitamin-in-life/
          - listitem:
            - link "Juice vs Direct Fruit":
              - /url: https://betteromation.shahrear.site/docs/juice-vs-direct-fruit/
          - listitem:
            - link "Watermelon – A Juicy Fruit":
              - /url: https://betteromation.shahrear.site/docs/watermelon-a-juicy-fruit/
      - article:
        - heading "Orange" [level=2]
        - list:
          - listitem:
            - link "The Fruit that Named after Color":
              - /url: https://betteromation.shahrear.site/docs/the-fruit-that-named-after-color/
          - listitem:
            - link "Orange – A Favorite Fruit of Children":
              - /url: https://betteromation.shahrear.site/docs/orange-a-favorite-fruit-of-children/
          - listitem:
            - link "Orange – The Source of Vitamin C":
              - /url: https://betteromation.shahrear.site/docs/orange-the-source-of-vitamin-c/
      - article:
        - heading "Apple" [level=2]
        - list:
          - listitem:
            - link "Apple – A Daily Fruit":
              - /url: https://betteromation.shahrear.site/docs/apple-a-daily-fruit/
  `);
});
