// @ts-check
const { test, expect } = require("@playwright/test");
const { safeGoto } = require("../helpers");
require("dotenv").config();

const BASE_URL = process.env.BASE_URL;

test("Category Box B Sleek - Snapshot", async ({ page }) => {
  await safeGoto(page, `${BASE_URL}/category-box-b-sleek/`);
  const content = page.locator("main#content");
  await expect(content).toBeVisible({ timeout: 10000 });
  await expect(content).toMatchAriaSnapshot(`
    - main:
      - heading "Category Box B Sleek" [level=1]
      - paragraph:
        - strong: BetterDocs Order
      - 'link "Cricket 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/cricket/
        - img
        - heading "Cricket" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Football 1 Doc Last Updated: January 27, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/football/
        - img
        - heading "Football" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: January 27, 2026"
      - 'link "Basketball 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/basketball/
        - img
        - heading "Basketball" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Golf 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/golf/
        - img
        - heading "Golf" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Fencing 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/fencing/
        - img
        - heading "Fencing" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Apple 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/apple/
        - img
        - heading "Apple" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Orange 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/orange/
        - img
        - heading "Orange" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Watermelon 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/watermelon/
        - img
        - heading "Watermelon" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Leads 2 Sub Categories | 1 Doc Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/lead/
        - img
        - heading "Leads" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Coleads 1 Sub Category | 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/coleads/
        - heading "Coleads" [level=2]
        - text: 1 Sub Category | 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Developer 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/developer/
        - img
        - heading "Developer" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "JuniorQA 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/juniorqa/
        - img
        - heading "JuniorQA" [level=2]
        - text: 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Star 2 Sub Categories | 1 Doc Last Updated: January 15, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/qa/star/
        - img
        - heading "Star" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: January 15, 2026"
      - heading "Name Based Order" [level=2]:
        - strong: Name Based Order
      - 'link "Apple 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/apple/
        - img
        - heading "Apple" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Basketball 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/basketball/
        - img
        - heading "Basketball" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Coleads 1 Sub Category | 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/coleads/
        - heading "Coleads" [level=2]
        - text: 1 Sub Category | 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Cricket 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/cricket/
        - img
        - heading "Cricket" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Developer 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/developer/
        - img
        - heading "Developer" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Fencing 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/fencing/
        - img
        - heading "Fencing" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Football 1 Doc Last Updated: January 27, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/football/
        - img
        - heading "Football" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: January 27, 2026"
      - 'link "Golf 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/golf/
        - img
        - heading "Golf" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "JuniorQA 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/juniorqa/
        - img
        - heading "JuniorQA" [level=2]
        - text: 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Leads 2 Sub Categories | 1 Doc Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/lead/
        - img
        - heading "Leads" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "MSF 1 Doc Last Updated: January 15, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/qa/msf/
        - img
        - heading "MSF" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: January 15, 2026"
      - 'link "Orange 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/orange/
        - img
        - heading "Orange" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Star 2 Sub Categories | 1 Doc Last Updated: January 15, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/qa/star/
        - img
        - heading "Star" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: January 15, 2026"
      - 'link "Watermelon 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/watermelon/
        - img
        - heading "Watermelon" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - heading "MKB Based – Team – ID – Descending" [level=2]
      - 'link "JuniorQA 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/juniorqa/
        - img
        - heading "JuniorQA" [level=2]
        - text: 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Developer 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/developer/
        - img
        - heading "Developer" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Coleads 1 Sub Category | 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/coleads/
        - heading "Coleads" [level=2]
        - text: 1 Sub Category | 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Leads 2 Sub Categories | 1 Doc Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/lead/
        - img
        - heading "Leads" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: March 31, 2026"
      - heading "Include – BetterDocs" [level=2]
      - 'link "Football 1 Doc Last Updated: January 27, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/football/
        - img
        - heading "Football" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: January 27, 2026"
      - 'link "Basketball 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/basketball/
        - img
        - heading "Basketball" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Orange 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/orange/
        - img
        - heading "Orange" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "MSF 1 Doc Last Updated: January 15, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/qa/msf/
        - img
        - heading "MSF" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: January 15, 2026"
      - heading "Exclude – Slug – Descending" [level=2]
      - 'link "Watermelon 3 Docs Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/watermelon/
        - img
        - heading "Watermelon" [level=2]
        - text: 3 Docs
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Star 2 Sub Categories | 1 Doc Last Updated: January 15, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/qa/star/
        - img
        - heading "Star" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: January 15, 2026"
      - 'link "Leads 2 Sub Categories | 1 Doc Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/lead/
        - img
        - heading "Leads" [level=2]
        - text: 2 Sub Categories | 1 Doc
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "JuniorQA 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/juniorqa/
        - img
        - heading "JuniorQA" [level=2]
        - text: 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Golf 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/golf/
        - img
        - heading "Golf" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Fencing 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/fencing/
        - img
        - heading "Fencing" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Developer 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/developer/
        - img
        - heading "Developer" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
      - 'link "Cricket 1 Doc Last Updated: December 15, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/sports/cricket/
        - img
        - heading "Cricket" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: December 15, 2025"
      - 'link "Coleads 1 Sub Category | 2 Docs Last Updated: March 31, 2026"':
        - /url: https://betteromation.shahrear.msf.bd/docs/team/coleads/
        - heading "Coleads" [level=2]
        - text: 1 Sub Category | 2 Docs
        - paragraph: "Last Updated: March 31, 2026"
      - 'link "Apple 1 Doc Last Updated: October 12, 2025"':
        - /url: https://betteromation.shahrear.msf.bd/docs/fruits/apple/
        - img
        - heading "Apple" [level=2]
        - text: 1 Doc
        - paragraph: "Last Updated: October 12, 2025"
  `);
});
